title: Taylor Gosselin's Blog 
author: Taylor Gosselin
email: "trgosselin14@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  I am currently a data engineer for a CRO specializing in Medical Imaging, Pathology,
  and Genomics. I use this site to share some design patterns I have found useful.
minima:
  skin: solarized-dark
linkedin_username: trgosselin
github_username:  trgosselin


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
